name: calcuttanode_app
description: Calcutta Node. - Mobile App for Clients
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  provider: ^6.1.2
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
